proxy:
  title: shinyproxy dev server
  logo-url: https://www.bms-uat-test.net/ibpworkbench/controller/static/images/logo.png
  port: 8080
  template-path: ./templates/bms_shinyapps
  docker:
      internal-networking: true
  specs:
  - id: stabrapp
    display-name: stabrapp
    description: "sprint 7 and minor bug fixes (as of 15/03/22)"
    container-cmd: ["R", "-e", "shinybrapps::run_stabrapp()"]
    container-image: shinybrapps
    container-network: shinyproxy-network
  - id: decision_support
    display-name: Decision support tool
    description: "sprint 3 (as of 18/03/22)"
    container-cmd: ["R", "-e", "shinybrapps::run_decision()"]
    container-image: shinybrapps
    container-network: shinyproxy-network
  - id: test
    display-name: test app
    description: displays hello world
    container-cmd: ["R", "-e", "shinybrapps::run_test()"]
    container-image: shinybrapps
    container-network: shinyproxy-network

logging:
  file:
    shinyproxy.log
