---
title: "GxE Stability Analysis Report"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y - %H:%M:%S')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(statgenGxE)
```
```{r, echo=FALSE}
htmltools::img(src = "sticker.png", 
               alt = 'logo',
               width = '150px',
               style = 'position:absolute; top:0; left:0; padding:10px;')
```

## Studies:
```{r}
TD <- unique(rbindlist(rv$TD)[,.(studyDbId, `Environment Name`=trial)])
knitr::kable(TD[unique(rv_gxe$data[,.(trialName, locationName, studyDbId, studyName)])[studyDbId%in%input$picker_env], on=.(studyDbId)])
```

## Trait: `r input$picker_trait`
## Stability measures
- S: Static stability (environmental variance)
- sqrtS: $\sqrt{S}$
- W: Wricke's ecovalence
- sqrtWe: $\sqrt{\frac{W}{Ne}}$, Ne: number of environments
- Sup: Superiority measure of Lin and Binns
```{r, echo=FALSE}
knitr::kable(rv_gxe$TDStab$dtres[order(!rv_gxe$TDStab$dtres$Genotype%in%rv_gxe$STSclicked_genotypes),])
```

### Stability plots

### Static stability
```{r, fig.height=10, fig.width=10, results='hide', warning=FALSE, message=FALSE}
        gg <- ggplot(rv_gxe$TDStab$dtres) + 
          geom_point(aes(x=Mean, y= sqrt(S))) +
          ylab("Square root of Static stability")
        rv_gxe$st_sta_plotdat <- gg$data
        if (input$STAB_plots_colorby!="Nothing"){
          #browser() 
          geompdat <- as.data.table(gg$data)
          geompdat <- merge.data.table(x=geompdat, y=unique(rbindlist(rv$TD)[,.SD,.SDcols=c("genotype",input$STAB_plots_colorby)]), by.x = "Genotype", by.y = "genotype", all = TRUE)
          gg$layers[[which(unlist(lapply(gg$layers, function(a) class(a$geom)[1]))=="GeomPoint")[1]]] <- NULL
          
          gg + ggnewscale::new_scale_fill() + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data=geompdat, aes(x=Mean, y= sqrtS, color=as.factor(.data[[input$STAB_plots_colorby]]), fill = as.factor(.data[[input$STAB_plots_colorby]]))) + 
            scale_fill_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none") + 
            scale_color_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none")
        }
        if(length(rv_gxe$STSclicked_genotypes)>0){
          clickgeno <- gg$data[gg$data$Genotype%in%rv_gxe$STSclicked_genotypes,]
          #browser()
          #gg + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data = clickgeno, aes(x=Mean , y = sqrt(S)), shape = 21, size=3, color="red") + 
            geom_text(data = clickgeno, aes(x=Mean , y = sqrt(S), label=Genotype), size=3, color="red",
                      position = position_nudge(y=max(sqrt(gg$data[,"S"]))/50))
          
        }
        gg
```

### Wricke ecovalence
```{r, fig.height=10, fig.width=10, results='hide', warning=FALSE, message=FALSE}
        gg <- ggplot(rv_gxe$TDStab$dtres) + 
          geom_point(aes(x=Mean, y= sqrtWe)) +
          ylab("Square root of Wricke ecovalence/Ne")
        rv_gxe$st_stw_plotdat <- gg$data
        if (input$STAB_plots_colorby!="Nothing"){
          #browser() 
          geompdat <- as.data.table(gg$data)
          geompdat <- merge.data.table(x=geompdat, y=unique(rbindlist(rv$TD)[,.SD,.SDcols=c("genotype",input$STAB_plots_colorby)]), by.x = "Genotype", by.y = "genotype", all = TRUE)
          gg$layers[[which(unlist(lapply(gg$layers, function(a) class(a$geom)[1]))=="GeomPoint")[1]]] <- NULL

          
          gg + ggnewscale::new_scale_fill() + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data=geompdat, aes(x=Mean, y= sqrtWe, color=as.factor(.data[[input$STAB_plots_colorby]]), fill = as.factor(.data[[input$STAB_plots_colorby]]))) + 
            scale_fill_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none") + 
            scale_color_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none")
        }
        if(length(rv_gxe$STSclicked_genotypes)>0){
          clickgeno <- gg$data[gg$data$Genotype%in%rv_gxe$STSclicked_genotypes,]
          #browser()
          #gg + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data = clickgeno, aes(x=Mean , y = sqrtWe), shape = 21, size=3, color="red") +
            geom_text(data = clickgeno, aes(x=Mean , y = sqrtWe, label=Genotype), size=3, color="red",
                      position = position_nudge(y=max(gg$data[,"sqrtWe"])/50))
          
        }
        gg
```

### Superiority
```{r, fig.height=10, fig.width=10, results='hide', warning=FALSE, message=FALSE}
        gg <- ggplot(rv_gxe$TDStab$dtres) + 
          geom_point(aes(x=Mean, y= sqrt(Sup))) +
          ylab("Square root of superiority")
        rv_gxe$st_sup_plotdat <- gg$data
        if (input$STAB_plots_colorby!="Nothing"){
          #browser() 
          geompdat <- as.data.table(gg$data)
          geompdat <- merge.data.table(x=geompdat, y=unique(rbindlist(rv$TD)[,.SD,.SDcols=c("genotype",input$STAB_plots_colorby)]), by.x = "Genotype", by.y = "genotype", all = TRUE)
          gg$layers[[which(unlist(lapply(gg$layers, function(a) class(a$geom)[1]))=="GeomPoint")[1]]] <- NULL
          
          gg + ggnewscale::new_scale_fill() + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data=geompdat, aes(x=Mean, y= sqrt(Sup), color=as.factor(.data[[input$STAB_plots_colorby]]), fill = as.factor(.data[[input$STAB_plots_colorby]]))) + 
            scale_fill_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none") + 
            scale_color_manual(values=getOption("statgen.genoColors"), na.value = "forestgreen", guide="none")
        }
        if(length(rv_gxe$STSclicked_genotypes)>0){
          clickgeno <- gg$data[gg$data$Genotype%in%rv_gxe$STSclicked_genotypes,]
          #browser()
          #gg + ggnewscale::new_scale_color()
          gg <- gg + geom_point(data = clickgeno, aes(x=Mean , y = sqrt(Sup)), shape = 21, size=3, color="red") +
            geom_text(data = clickgeno, aes(x=Mean , y = sqrt(Sup), label=Genotype), size=3, color="red",
                      position = position_nudge(y=max(sqrt(gg$data[,"Sup"]))/50))
        }
        gg
```