---
title: "GxE GGE Analysis Report"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y - %H:%M:%S')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(statgenGxE)
library(metan)
```

## Studies:
```{r}
TD <- unique(rbindlist(rv$TD)[,.(studyDbId, `Environment Name`=trial)])
knitr::kable(TD[unique(rv_gxe$data[,.(trialName, locationName, studyDbId, studyName)])[studyDbId%in%input$picker_env], on=.(studyDbId)])
```

## Trait: `r input$picker_trait`
## Analysis output
```{r, echo=FALSE}
TD.metangge <- rbindlist(rv$TD)[,.SD, .SDcols=c("trial","genotype",input$picker_trait)]

TDGGEmetan <- tryCatch(metan::gge(TD.metangge,
                                     env=trial,
                                     gen=genotype,
                                     resp = input$picker_trait,
                                     centering = input$GGE_advs_centering,
                                     scaling = input$GGE_advs_scaling,
                                     svp = input$GGE_advs_svp,), error=function(e) e)
TDGGE <- tryCatch(gxeGGE(TD = rv$TD, trait = input$picker_trait, useWt = input$use_weights), error=function(e) e)
          if ("AMMI"%in%class(rv_gxe$TDGGE)){
            summary(rv_gxe$TDGGE)
          } 


```

## GGE plots

```{r, fig.height=10, fig.width=10, results='hide', warning=FALSE, message=FALSE}
TDGGEplot <- TDGGEmetan
lapply(1:10, function(ptype){
  if (ptype==5){
            metan:::plot.gge(TDGGEplot,
                             type = ptype,
                             sel_env = input$GGE_picker_env_select,
                             size.text.gen = input$GGE_plot_size.text.gen,
                             repulsion = input$GGE_plot_repulsion,
                             max_overlaps = input$GGE_plot_max_overlaps,
                             size.shape = input$GGE_plot_size.shape,
                             size.shape.win = input$GGE_plot_size.shape.win,
                             size.stroke = input$GGE_plot_size.stroke,
                             col.alpha = input$GGE_plot_col.alpha,
                             col.alpha.circle = input$GGE_plot_col.alpha.circle,
                             size.text.env = input$GGE_plot_size.text.env,
                             size.text.lab = input$GGE_plot_size.text.lab,
                             size.text.win = input$GGE_plot_size.text.win,
                             size.line = input$GGE_plot_size.line,
                             axis_expand = input$GGE_plot_axis_expand,
                             col.stroke = input$GGE_plot_col.stroke,
                             col.gen = input$GGE_plot_col.gen,
                             col.env = input$GGE_plot_col.env,
                             col.line = input$GGE_plot_col.line,
                             col.circle = input$GGE_plot_col.circle,
                             plot_theme = metan:::theme_metan() %+replace% theme(plot.title = element_text(size = input$GGE_plot_title_size, face = "bold", hjust = 0, vjust = 3),
                                                                                 plot.subtitle = element_text(size = input$GGE_plot_title_size-2, face = "italic", hjust = 0, vjust = 2))
            )            
            
          } else if (ptype == 7) {
            metan:::plot.gge(TDGGEplot,
                             type = ptype,
                             sel_gen = input$GGE_picker_gen_select,
                             size.text.gen = input$GGE_plot_size.text.gen,
                             repulsion = input$GGE_plot_repulsion,
                             max_overlaps = input$GGE_plot_max_overlaps,
                             size.shape = input$GGE_plot_size.shape,
                             size.shape.win = input$GGE_plot_size.shape.win,
                             size.stroke = input$GGE_plot_size.stroke,
                             col.alpha = input$GGE_plot_col.alpha,
                             col.alpha.circle = input$GGE_plot_col.alpha.circle,
                             size.text.env = input$GGE_plot_size.text.env,
                             size.text.lab = input$GGE_plot_size.text.lab,
                             size.text.win = input$GGE_plot_size.text.win,
                             size.line = input$GGE_plot_size.line,
                             axis_expand = input$GGE_plot_axis_expand,
                             col.stroke = input$GGE_plot_col.stroke,
                             col.gen = input$GGE_plot_col.gen,
                             col.env = input$GGE_plot_col.env,
                             col.line = input$GGE_plot_col.line,
                             col.circle = input$GGE_plot_col.circle,
                             plot_theme = metan:::theme_metan() %+replace% theme(plot.title = element_text(size = input$GGE_plot_title_size, face = "bold", hjust = 0, vjust = 3),
                                                                                 plot.subtitle = element_text(size = input$GGE_plot_title_size-2, face = "italic", hjust = 0, vjust = 2))
            )
          } else if (ptype == 9) {
            metan:::plot.gge(TDGGEplot,
                             type = ptype,
                             sel_gen1 = input$GGE_picker_gen_select,
                             sel_gen2 = input$GGE_picker_gen2_select,
                             size.text.gen = input$GGE_plot_size.text.gen,
                             repulsion = input$GGE_plot_repulsion,
                             max_overlaps = input$GGE_plot_max_overlaps,
                             size.shape = input$GGE_plot_size.shape,
                             size.shape.win = input$GGE_plot_size.shape.win,
                             size.stroke = input$GGE_plot_size.stroke,
                             col.alpha = input$GGE_plot_col.alpha,
                             col.alpha.circle = input$GGE_plot_col.alpha.circle,
                             size.text.env = input$GGE_plot_size.text.env,
                             size.text.lab = input$GGE_plot_size.text.lab,
                             size.text.win = input$GGE_plot_size.text.win,
                             size.line = input$GGE_plot_size.line,
                             axis_expand = input$GGE_plot_axis_expand,
                             col.stroke = input$GGE_plot_col.stroke,
                             col.gen = input$GGE_plot_col.gen,
                             col.env = input$GGE_plot_col.env,
                             col.line = input$GGE_plot_col.line,
                             col.circle = input$GGE_plot_col.circle,
                             plot_theme = metan:::theme_metan() %+replace% theme(plot.title = element_text(size = input$GGE_plot_title_size, face = "bold", hjust = 0, vjust = 3),
                                                                                 plot.subtitle = element_text(size = input$GGE_plot_title_size-2, face = "italic", hjust = 0, vjust = 2))
            )
          } else {
            gg <- metan:::plot.gge(TDGGEplot,
                             type = ptype,
                             size.text.gen = input$GGE_plot_size.text.gen,
                             repulsion = input$GGE_plot_repulsion,
                             max_overlaps = input$GGE_plot_max_overlaps,
                             size.shape = input$GGE_plot_size.shape,
                             size.shape.win = input$GGE_plot_size.shape.win,
                             size.stroke = input$GGE_plot_size.stroke,
                             col.alpha = input$GGE_plot_col.alpha,
                             col.alpha.circle = input$GGE_plot_col.alpha.circle,
                             size.text.env = input$GGE_plot_size.text.env,
                             size.text.lab = input$GGE_plot_size.text.lab,
                             size.text.win = input$GGE_plot_size.text.win,
                             size.line = input$GGE_plot_size.line,
                             axis_expand = input$GGE_plot_axis_expand,
                             col.stroke = input$GGE_plot_col.stroke,
                             col.gen = input$GGE_plot_col.gen,
                             col.env = input$GGE_plot_col.env,
                             col.line = input$GGE_plot_col.line,
                             col.circle = input$GGE_plot_col.circle,
                             plot_theme = metan:::theme_metan() %+replace% theme(plot.title = element_text(size = input$GGE_plot_title_size, face = "bold", hjust = 0, vjust = 3),
                                                                                 plot.subtitle = element_text(size = input$GGE_plot_title_size-2, face = "italic", hjust = 0, vjust = 2))
            )
                  if ((input$GGE_colorGenoBy!="Nothing" || input$GGE_colorEnvBy!="Nothing") & ptype==1){
          geompdat <- as.data.table(gg$data)
          
          if (input$GGE_colorGenoBy!="Nothing"){
            geompdat <- merge.data.table(x=geompdat, 
                                         y=setnames(unique(rbindlist(rv$TD)[,.SD,.SDcols=c("genotype",input$GGE_colorGenoBy)]),new = c("genotype","colorby1")),
                                         by.x = "label", by.y = "genotype", all = TRUE)
          } else {
            geompdat[, colorby1:=NA]
          }
          if (input$GGE_colorEnvBy!="Nothing"){
            geompdat <- merge.data.table(x=geompdat, 
                                         y=setnames(unique(rbindlist(rv$TD)[,.SD,.SDcols=c("trial",input$GGE_colorEnvBy)]),new = c("trial","colorby2")),
                                         by.x = "label", by.y = "trial", all = TRUE)
          } else {
            geompdat[, colorby2:=NA]
          }
          geompdat[, colorby:=""]
          geompdat[is.na(colorby1), colorby:=colorby2]
          geompdat[is.na(colorby2), colorby:=colorby1]

          gg$layers[[which(unlist(lapply(gg$layers, function(a) class(a$geom)[1]))=="GeomPoint")[1]]] <- NULL

          if (input$GGE_colorGenoBy!="Nothing"){
            gg <- gg + ggnewscale::new_scale_fill() + ggnewscale::new_scale_color()
            gg <- gg + geom_point(data=geompdat[type=="genotype"], 
                                  aes(d1, d2, color=as.factor(.data[["colorby"]]), 
                                      fill = as.factor(.data[["colorby"]])), 
                                  shape = 21, 
                                  size = input$GGE_plot_size.shape, 
                                  stroke = input$GGE_plot_size.stroke, 
                                  alpha = input$GGE_plot_col.alpha) + 
            scale_fill_manual(values=getOption("statgen.genoColors")) + 
            scale_color_manual(values=getOption("statgen.genoColors"), guide="none") 
          } else {
            gg <- gg + geom_point(data=geompdat[type=="genotype"], 
                                  aes(d1, d2, color=as.factor(.data[["colorby"]])), 
                                  shape = 21, color= input$GGE_plot_col.stroke, 
                                  fill= input$GGE_plot_col.gen, 
                                  size = input$GGE_plot_size.shape,
                                  stroke = input$GGE_plot_size.stroke, 
                                  alpha = input$GGE_plot_col.alpha) 
          }
          if (input$GGE_colorEnvBy!="Nothing"){
            gg <- gg + ggnewscale::new_scale_fill() + ggnewscale::new_scale_color()
            gg <- gg + geom_point(data=geompdat[type=="environment"], 
                                  aes(d1, d2, color=as.factor(.data[["colorby"]]), 
                                      fill = as.factor(.data[["colorby"]])), 
                                  shape = 23, size = input$GGE_plot_size.text.env, 
                                  stroke = input$GGE_plot_size.stroke, 
                                  alpha = input$GGE_plot_col.alpha) + 
            scale_fill_manual(values=getOption("statgen.trialColors")) + 
            scale_color_manual(values=getOption("statgen.trialColors"), guide="none")
          } else {
            gg <- gg + geom_point(data=geompdat[type=="environment"], 
                                  aes(d1, d2, color=as.factor(.data[["colorby"]])), 
                                  shape = 23, color= input$GGE_plot_col.stroke, 
                                  fill= input$GGE_plot_col.env, 
                                  size = input$GGE_plot_size.text.env, 
                                  stroke = input$GGE_plot_size.stroke, 
                                  alpha = input$GGE_plot_col.alpha) 
          }
          
          if (input$GGE_colorGenoBy!="Nothing" & input$GGE_colorEnvBy!="Nothing") {
            gg <- gg + guides(fill = guide_legend(override.aes = list(shape=21))) + guides(fill = guide_legend(override.aes = list(shape=23)))
          } else if (input$GGE_colorGenoBy!="Nothing") {
            gg <- gg + guides(fill = guide_legend(override.aes = list(shape=21)), shape = "none")
          } else if (input$GGE_colorEnvBy!="Nothing"){
            gg <- gg + guides(fill = guide_legend(override.aes = list(shape=23)), size = "none")
          } else {
            gg <- gg + guides(fill = "none")
          }
        }
        if(length(rv_gxe$GGEclicked_genotypes)>0){
          clickgeno <- gg$data[gg$data$type=="genotype" & gg$data$label%in%rv_gxe$GGEclicked_genotypes,]
          gg + ggnewscale::new_scale_fill()
          gg <- gg + geom_point(data = clickgeno, aes(x=d1, y = d2), shape = 21, size=input$GGE_plot_size.shape+2, stroke=input$GGE_plot_size.stroke, color="red") 
        }
        gg + theme(legend.position.inside=NULL, legend.position = "right")

            }
})
```

