FROM rocker/verse:4.5.0

## Install debian libs
RUN apt-get update && apt-get install -y \
	binutils \
	libxml2-dev \
	libssl-dev \
	libcurl4-openssl-dev \
	libgdal-dev \
	libfontconfig1-dev \
	pandoc \
	cmake \
	libharfbuzz-dev \
	libfribidi-dev

## Golem Dockerfile
#RUN apt-get update -y && apt-get install -y  make pandoc zlib1g-dev libx11-dev libcurl4-openssl-dev libssl-dev libicu-dev git && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = FALSE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "1.0.3")'
COPY renv.lock renv.lock

RUN --mount=type=cache,id=renv-cache,target=/root/.cache/R/renv R -e 'renv::restore()'
